### ISSUE TITLE
As i check the link, the demo app its not working

### ISSUE THREAD

**Issue by donPuerto** [dlodeprojuicer/ionic-vue-mobile-template-04#1]
![image](https://user-images.githubusercontent.com/9329005/94257908-9a5cc080-ff5e-11ea-974c-7b64ea0ecde1.png)

This is very nice start up template

**Comment by dlodeprojuicer** [comment]
@donPuerto thanks for feedback. I suspect its Netlify glitch. 

I see the header has some css issues there. I will look into that.

**Comment by dlodeprojuicer** [comment]
Fixed in commit [2548f0b](https://github.com/dlodeprojuicer/ionic-vue-mobile-template-04/commit/2548f0b51f71a88e4f515e1f92198ca30a3c051f)
